# Generated by Django 3.2.2 on 2021-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="telegramaccount",
            name="pincode",
            field=models.IntegerField(default=0),
        )
    ]
