# Generated by Django 3.2.2 on 2021-05-09 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0002_telegramaccount_pincode")]

    operations = [
        migrations.CreateModel(
            name="States",
            fields=[
                ("state_id", models.IntegerField(primary_key=True, serialize=False)),
                ("state_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Disrtict",
            fields=[
                ("district_id", models.IntegerField(primary_key=True, serialize=False)),
                ("district_name", models.CharField(max_length=100)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.states"
                    ),
                ),
            ],
        ),
    ]
