# Generated by Django 3.2.2 on 2021-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0003_auto_20210510_0621")]

    operations = [
        migrations.AddField(
            model_name="telegramaccount",
            name="total_alerts_18",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="telegramaccount",
            name="total_alerts_45",
            field=models.IntegerField(default=0),
        ),
    ]
